### ISSUE TITLE
Plugin URL

### ISSUE THREAD

**Issue by xDefcon** [BtoBastian/bStats#17] opened 2017-02-14 20:14 UTC
It would be nice to have a Bukkit/Spigot/Sponge **URL** of the plugin.

Example:

- Plugin name: TestPlugin
- Plugin URL: https://www.spigotmc.org/resources/something/

**Comment by BtoBastian** [comment] 2017-02-14 21:21
Hey, 
plugin pages will be much more customizable in the future, but it may take some time to implement it.
There are other features which have a higher priority (e.g. increasing reliability by supporting cluster mode)  at the moment. However this feature is definitely on my TODO list.

PS: I'll close this issue, cause it's some kind of duplicate of issue #1

**Closed by BtoBastian** 2017-02-14 21:21 UTC
Labels: duplicate, enhancement
